- .travis.yml
- Makefile
- stack.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/1)
> Only fetch 1 revision from git during Travis builds.

- .travis.yml
- Makefile
- stack.yaml
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/2)
> Add libdir-self-perl to the apt dependency list.

- WORKSPACE
- third_party/BUILD.ghc
- third_party/haskell/BUILD.MissingH
- third_party/haskell/BUILD.hslogger
- third_party/haskell/BUILD.network
- third_party/haskell/BUILD.old-time
- tools/bazel.rc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/11)
> Disable remote cache; add @haskell_old_time.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/12)
> Add travis local caching.

- .travis.yml
- BUILD.bazel
- LICENSE.md
Affero has questionable legal enforceability and its concrete
requirements and reach are unclear. For example, it is unclear
whether a public service that calls a public AGPL service must be
AGPL. One might say no, but then would a public service calling an
internally hosted version of that same public AGPL service be AGPL?
If the answer is no, then AGPL is not enforceable.
More importantly, this lack of clarity and other issues around
Affero make it a poor choice of license, making lawyers nervous and
developers shy away from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/13)
> Relicense under GPLv3.

- .gitmodules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/19)
> Add cedar to the toktok stack.

- .gitmodules
- .travis.yml
- BUILD.bazel
- README.md
- WORKSPACE
- third_party/BUILD.libsodium
- third_party/android/.gitignore
- third_party/haskell/BUILD.aeson-compat
- third_party/haskell/BUILD.binary-orphans
- third_party/haskell/BUILD.tf-random
- third_party/haskell/BUILD.vector-binary-instances
- tools/bazel.rc
- tools/project.bzl
- tools/project/BUILD.bazel
- tools/project/license_test.sh
- tools/project/readme_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/20)
> Add a bazel test that ensures all our projects are GPL-3.0.

- .travis.yml
- BUILD.bazel
- WORKSPACE
- stack.yaml
- third_party/haskell/BUILD.cpphs
- third_party/haskell/BUILD.groom
- third_party/haskell/BUILD.haskell-src-exts
- third_party/haskell/BUILD.language-c
- third_party/haskell/BUILD.lens-family
- third_party/haskell/BUILD.lens-family-core
- third_party/haskell/BUILD.polyparse
- third_party/qt/build_defs.bzl
- third_party/yasm/build_defs.bzl
- tools/bazel-0.11.0-without-jdk-installer-linux-x86_64.sh.sha256
- tools/bazel-0.14.1-installer-linux-x86_64.sh.sha256
- tools/bazel.rc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/23)
> Add lens-family haskell package (dependency for hstox).

- WORKSPACE
- third_party/BUILD.ffmpeg
- third_party/BUILD.x264
and tweak ffmpeg configure options
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/27)
> add x264 local repository

- WORKSPACE
- tools/bazel.rc
This one properly supports clang-8.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/35)
> Upgrade to latest version of bazel-toolchains.

- .cirrus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/39)
> Enable yamllint for all repositories.

- .travis.yml
- README.md
- WORKSPACE
- third_party/BUILD.xdmcp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/47)
> Update X11 dependencies.

- README.md
- WORKSPACE
- third_party/qt/BUILD.bazel
- tools/setup-ci
- tools/workspace/local.bzl
- tools/workspace/python.bzl
- tools/workspace/qt.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/48)
> Simplify qTox build by autodetecting library locations.

- .travis.yml
- WORKSPACE
- third_party/BUILD.boringssl
- third_party/BUILD.curl
- third_party/BUILD.ffmpeg
- third_party/BUILD.openssl
- third_party/BUILD.sqlcipher
- tools/project/cabal_test.py
- tools/workspace/local.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/51)
> Fix build of @ffmpeg//:bin/ffplay on osx.

- .bazelrc
- WORKSPACE
- third_party/BUILD.openssl
- third_party/BUILD.sdl2
- third_party/BUILD.xcb
- third_party/curl/osx/curl_config.h
- tools/Dockerfile
- tools/setup-bazel
- tools/toktok-stack.sha256
Boringssl is configured with more options than the brew version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/52)
> Fix OSX build now that we no longer build our own openssl.

- .github/CODEOWNERS
This directory will contain a settings file that makes anyone with push
access admin of the repo. We protect it by requiring code review of an
existing admin, which means admins can add admins (they already can).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/63)
> Add CODEOWNERS file for /.github/.

- .github/settings.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/65)
> Add back the "bazel" tag for toktok-stack.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/70)
> Fix .bazelrc so it works in all directories, not just //.

- tools/workspace/python.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/78)
> Fix linking toxic against libpython 3.8.

- .bazelrc
- .bazelrc.local.example
- .cirrus.yml
- .travis.yml
- .ycm_extra_conf.py
- tools/kythe/builder.py
- tools/kythe/clang_tidy.py
- tools/kythe/ycm_extra_conf.py
We still need python3 to be installed, and use json to communicate with
the python3 binary running our YCM settings code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/86)
> Add support for YouCompleteMe in vim built with Python 2.

- .bazelrc
- .gitignore
- .travis.yml
- .typo-ci.yml
- tools/debug/BUILD.bazel
- tools/debug/malloc_debug.py
- tools/debug/mallocfail.c
- tools/debug/oomer.c
- tools/debug/run_mallocfail
- tools/debug/run_oomer
You can use it with any bazel C/C++ target, or with a binary that's
linked against tools/debug/oomer.c.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/91)
> Add "oomer" tool (run_oomer and library).

- .github/settings.yml
- .travis.yml
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/111)
> chore: Fix name of "upstream" remote for jtox.

- tools/debug/BUILD.bazel
- tools/debug/flakynet.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/118)
> feat: Add flakynet, a UDP packet loss testing library.

- .bazelrc
- WORKSPACE
- third_party/qt/build_defs.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/122)
> chore(deps): Update dependencies for macOS.

- .bazelrc
- .github/workflows/ci.yml
- third_party/BUILD.ffmpeg
We're not updating the toktok-stack version here, because none of the
modules depend on any other module's latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/201)
> chore: Update all submodules to the latest git version.

- .bazelrc
- Makefile
- tools/project/haskell_cirrus.yml.in
- tools/project/update_versions.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/229)
> chore: Update submodule versions.

- WORKSPACE
- tools/prepare_third_party.sh
This is taking too much space. GH actions run out of disk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/230)
> chore: Remove NDK from the docker image.

- .github/settings.yml
- .github/workflows/ci.yml
- .ycm_extra_conf.py
- tools/kythe/builder.py
- tools/kythe/ycm_extra_conf.py
Also, running the ycm script on CI to make sure it doesn't break again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/234)
> fix: Update ycm script to the latest kythe changes.

- third_party/haskell/BUILD.recursion-schemes
- third_party/haskell/BUILD.transformers-compat
- third_party/haskell/packages.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/247)
> chore: Add recursion-schemes to third_party haskell.

- .bazelrc
- .bazelrc.local.example
- .github/workflows/ci.yml
- Makefile
- tools/built/Makefile
- tools/built/src/Dockerfile.in
- tools/project/haskell_cirrus.yml.in
- tools/project/update_versions.sh
So we can have fast builds for both `--config=release` and
`--config=debug` on sub-repo builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/252)
> feat: Build both release and debug docker images.

- tools/built/Makefile
This isn't working for haskell code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/253)
> chore: Remove debug build again.

- tools/project/haskell/github/publish.yml
Also updated the Haskell publish workflow template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/259)
> chore: Update tokstyle in the stack.

- .github/workflows/ci.yml
- Makefile
- third_party/BUILD.bazel
- tools/built/Makefile
- tools/built/src/Dockerfile.debug
- tools/built/src/Dockerfile.release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/260)
> chore(deps): Update c-toxcore; add debug image build.

- third_party/haskell/BUILD.edit-distance
- third_party/haskell/packages.bzl
We'll use it to improve diagnostics in tokstyle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/262)
> chore: Add edit-distance haskell package.

- .github/workflows/ci.yml
- Dockerfile
- tools/built/bazel_test
We already build everything, but this takes it one step further and
ensures all tests globally pass on every update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/265)
> chore(deps): Run all tests on subrepo updates.

- .github/dependabot.yml
- Makefile
Also allow dependabot to open up to 2 PRs, so we can merge the more
important one first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/266)
> chore(deps): Update c-toxcore, ci-tools, and tokstyle.

- .bazelrc
- .github/workflows/ci.yml
- Dockerfile
- WORKSPACE
- third_party/BUILD.bazel
- third_party/BUILD.libvpx
- third_party/BUILD.tcl
- third_party/android/.gitignore
- third_party/android/sdk/.gitignore
- third_party/scala/BUILD.bazel
- third_party/scala/EmptyTest.scala
- third_party/scala/test.proto
- tools/bazel-4.2.1-installer-linux-x86_64.sh.sha256
- tools/bazelrc.boot
- tools/built/src/Dockerfile.release
- tools/prepare_toolchain.sh
The google builder image is broken. It uses an old java which is no
longer compatible with the latest bazel. We're now using our own image
from toxchat/bazel with Java 11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/275)
> chore: Use our own toolchain instead of the google one.

- tools/built/src/Dockerfile.asan
- tools/built/src/Dockerfile.debug
- tools/built/src/Dockerfile.msan
- tools/built/src/Dockerfile.release
- tools/built/src/Dockerfile.tsan
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/279)
> chore: Fix remote cache usage.

- .github/workflows/docker.yml
- tools/project/cabal_test.py
Also, checkout code in non-release docker image builds. Without that, we
can't build anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/283)
> fix: Support `package` in haskell packages.

- .github/workflows/docker.yml
Push happens only in the second step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/284)
> chore: Fix docker login on debug/asan/tsan/msan builds.

- tools/built/bazel_test
- tools/retry
Hopefully this can help the tsan bazel build for c-toxcore complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/287)
> feat: Add a `retry` script to run a command multiple times.

- tools/retry
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/289)
> chore: Return failure exit status if all retries fail.

- .bazelrc
- WORKSPACE
- third_party/patches/libsodium.patch
- third_party/patches/opus.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/293)
> chore: Add patches for libsodium and opus to pass msan.

- .bazelrc
- .restyled.yaml
- third_party/BUILD.libsodium
- third_party/libsodium/linux/sodium_config.h
- third_party/libsodium/version.h
It was missing some defines. With these, msan is happier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/295)
> fix: Update sodium_config.h for 1.0.18.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/297)
> chore: Give builder user passwordless sudo.

- .github/workflows/ci.yml
- Makefile
- tools/kythe/clang_tidy
- tools/kythe/ycm_extra_conf.py
- tools/project/BUILD.bazel
- tools/project/build_defs.bzl
- tools/project/cabal_test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/301)
> cleanup: Add mypy type checking to python scripts.

- .bazelrc
It broke stuff :(.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/304)
> chore: Disable `--remote_download_minimal` again.

- .bazelrc
- WORKSPACE
- third_party/python/build_defs.bzl
- tools/bazelrc.boot
It will be used for the pytox rewrite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/305)
> chore: Add cython to the dependencies.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/310)
> chore: Increase flaky test retries.

- .bazelrc
- .github/workflows/docker.yml
- .gitignore
- Dockerfile
- Makefile
- WORKSPACE
- third_party/BUILD.bazel
- third_party/BUILD.bazel_toolchain
- tools/bazelrc.boot
- tools/prepare_toolchain.sh
- tools/toolchain/.gitignore
This way, it can be used by dev containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/319)
> chore(rebuild): Move the toolchain out of workspace.

- .bazelrc.local.example
- .github/workflows/docker.yml
- tools/built/Makefile
- tools/built/src/Dockerfile.fastbuild
This way it also works on master push builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/321)
> chore: Use commit message in addition to PR title for skipping pull.

- .github/workflows/docker.yml
- tools/built/src/Dockerfile.asan
- tools/built/src/Dockerfile.debug
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.fastbuild
- tools/built/src/Dockerfile.msan
- tools/built/src/Dockerfile.release
- tools/built/src/Dockerfile.tsan
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/322)
> feat: Add dev container docker build.

- Makefile
- tools/built/Dockerfile
- tools/built/Makefile
- tools/built/built/.gitignore
- tools/built/init.sh
- tools/built/run_dev_container.sh
- tools/built/src/Dockerfile.asan
- tools/built/src/Dockerfile.debug
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.fastbuild
- tools/built/src/Dockerfile.msan
- tools/built/src/Dockerfile.release
- tools/built/src/Dockerfile.tsan
- tools/kythe/builder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/323)
> chore: Fix dev container build; add example usage.

- .bazel_fix_commands.json
- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/326)
> chore: Disable deprecated-declarations warning in cython code.

- .gitignore
- tools/built/src/Dockerfile.dev
- tools/project/haskell/cirrus.yml.in
"release" makes it "stateful" and take longer to schedule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/327)
> chore: Rename bazel build to "opt" in cirrus.

- .dockerignore
- .github/settings.yml
- .github/workflows/ci.yml
- .github/workflows/docker.yml
- tools/built/src/Dockerfile
- tools/built/src/Dockerfile.third_party
The makefile is complicated. This reduces that complexity trading off
some local reproducibility. This now only works well on a mostly-fresh
clone. On the GH action builds, reproducibility is still fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/331)
> chore: Rework docker image builds to use less magic.

- .dockerignore
- .github/settings.yml
- .github/workflows/ci.yml
- .github/workflows/docker.yml
- tools/built/src/Dockerfile.dev
The docker build push action already does this for us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/332)
> chore: Remove explicit checkout in buildx actions.

- .gitmodules
- tools/built/src/init.sh
- tools/git-remotes
- tools/prepare_third_party.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/339)
> chore: Add btox to the stack.

- tools/built/dev/Dockerfile
- tools/built/dev/deploy_dev_container.sh
- tools/built/src/Dockerfile.dev
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/344)
> feat: Install manpages in dev container.

- .hie-bios
- hie.yaml
- tools/BUILD.bazel
- tools/built/dev/deploy_dev_container.sh
- tools/built/src/Dockerfile.dev
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/345)
> feat: Make GHC with bazel work in vscode.

- tools/built/dev/Dockerfile
- tools/built/dev/deploy_dev_container.sh
- tools/built/dev/home/.local/share/zsh/.gitignore
- tools/built/dev/home/.vim/settings.vim
- tools/built/dev/home/.vimrc
- tools/built/dev/home/.zshrc
- tools/built/dev/run_dev_container.sh
- tools/built/src/init.sh
Also set the shiftwidth and tabstop settings appropriately for toxcore C
style (4 spaces).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/349)
> feat: Add more vim plugins for Haskell development.

- tools/built/dev/home/.vimrc
- tools/built/dev/home/.zshrc
Also added export for `GITHUB_TOKEN` if a `.github-token` exists in `$HOME`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/352)
> chore: Update submodules.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/359)
> chore: Update cimple.

- .bazelrc
`nonnull` -> `non_null`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/361)
> chore: Update cimple again.

- third_party/haskell/BUILD.Diff
- third_party/haskell/BUILD.aeson-pretty
- third_party/haskell/BUILD.cmdargs
- third_party/haskell/BUILD.expiring-cache-map
- third_party/haskell/BUILD.pretty
- third_party/haskell/packages.bzl
- tools/built/src/Dockerfile.release
Needed for github-tools webservice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/367)
> chore(rebuild): Add additional haskell deps.

- WORKSPACE
Used for websockify.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/373)
> chore(rebuild): Update submodules; add websocket go dependency.

- tools/built/dev/Dockerfile
- tools/built/dev/home/.config/procps/toprc
- tools/built/dev/home/.vimrc
- tools/built/dev/home/.zshrc
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.dev-hs
- tools/built/src/init.sh
- tools/built/src/setup-local.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/374)
> feat: Add heroku API to the dev image.

- tools/built/dev/Dockerfile
- tools/built/dev/home/.config/procps/toprc
- tools/built/dev/home/.vimrc
- tools/built/dev/home/.zshrc
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.dev-hs
- tools/built/src/Dockerfile.haskell
- tools/built/src/init.sh
- tools/built/src/setup-local.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/375)
> chore: Enable tests on haskell stack builds.

- .gitmodules
- stack.yaml
- third_party/haskell/BUILD.persist
- third_party/haskell/packages.bzl
- tools/BUILD.bazel
- tools/built/dev/home/.vimrc
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/376)
> chore: Add hs-msgpack-persist to the stack.

- tools/built/src/Dockerfile.haskell
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/377)
> chore: Add missing hs-msgpack-persist to dockerfile.

- .github/settings.yml
- .github/workflows/ci.yml
- .gitmodules
- stack.yaml
- tools/project/haskell/github/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/380)
> chore: Add msgpack-testsuite to the stack.

- .gitmodules
- stack.yaml
- tools/BUILD.bazel
- tools/built/src/Dockerfile.haskell
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/383)
> chore: Add msgpack-arbitrary to the stack.

- .github/settings.yml
- .github/workflows/ci.yml
This one can break easily so we want to test it before merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/384)
> chore: Run stack build before PR merge.

- .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/386)
> chore: Update msgpack-arbitrary.

- .bazelrc
- tools/debug/malloc_debug.py
- tools/debug/run_mallocfail
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/393)
> feat: Add `--config=mallocfail` and fix run_mallocfail.

- tools/built/dev/home/.vimrc
This matches the toktok style a bit better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/395)
> chore: Slightly better haskell indent settings in vim.

- .bazelrc
- .gitignore
- third_party/BUILD.ncurses
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/417)
> chore: Add wchar ncurses support.

- third_party/haskell/BUILD.brick
- third_party/haskell/BUILD.config-ini
- third_party/haskell/BUILD.data-clist
- third_party/haskell/BUILD.megaparsec
- third_party/haskell/BUILD.microlens
- third_party/haskell/BUILD.microlens-mtl
- third_party/haskell/BUILD.microlens-th
- third_party/haskell/BUILD.parser-combinators
- third_party/haskell/BUILD.text-zipper
- third_party/haskell/BUILD.vty
- third_party/haskell/BUILD.word-wrap
- third_party/haskell/packages.bzl
Used for text-based UIs in Haskell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/420)
> chore: Add brick (and dependencies) to third_party.

- .restyled.yaml
- third_party/haskell/happy/templates/HappyTemplate
- third_party/haskell/happy/templates/HappyTemplate-arrays
- third_party/haskell/happy/templates/HappyTemplate-arrays-coerce
- third_party/haskell/happy/templates/HappyTemplate-arrays-coerce-debug
- third_party/haskell/happy/templates/HappyTemplate-arrays-debug
- third_party/haskell/happy/templates/HappyTemplate-arrays-ghc
- third_party/haskell/happy/templates/HappyTemplate-arrays-ghc-debug
- third_party/haskell/happy/templates/HappyTemplate-coerce
- third_party/haskell/happy/templates/HappyTemplate-ghc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/426)
> chore: Update happy parser templates.

- .bazelrc
- third_party/BUILD.libidn2
- third_party/libidn2/BUILD.bazel
- third_party/libidn2/c_isupper.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/444)
> chore: Enable optimisation flags in sanitizer builds.

- .gitmodules
- WORKSPACE
- tools/BUILD.bazel
- tools/git-remotes
This can then be used in hermetic tests.
Also upgrade some deps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/451)
> chore: Add toktok-fuzzer to the stack.

- .bazelrc
It was `-U_NDEBUG` which does nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/456)
> chore: Fix the `-UNDEBUG` flag.

- .bazelrc
- .gitignore
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/458)
> chore: Add cmp to the git-remotes script.

- .bazelrc
This enables `__attribute__((__nonnull__))`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/459)
> test: Enable `_DEBUG` in toxcore.

- .bazelrc
This is an alternative to libfuzzer and can possibly find a different
set of fuzz inputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/488)
> chore: Add honggfuzz bazel config.

- .github/workflows/docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/627)
> chore: Update docker actions from v1 to v2.

- third_party/BUILD.tcl
- third_party/haskell/BUILD.language-c
- tools/built/src/setup-dev.sh
These contain fixes for failing tests. After this, the dev container build should work again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/632)
> chore: Update some repos.

- tools/built/src/setup-dev.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/633)
> chore: Fix buildtools version reference.

- .bazelrc
- .github/workflows/docker.yml
- tools/built/src/home/.config/home-manager/home.nix
- tools/built/src/setup-dev.sh
- tools/project/haskell/cirrus.yml.in
- tools/workspace/github.bzl
msan still broken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/673)
> cleanup: Fix asan/tsan builds; re-enable them on CI.

- .github/workflows/docker.yml
- tools/bazelrc.docker
- tools/built/src/home/.config/home-manager/home.nix
Also set `--config=docker` on docker images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/675)
> chore: Enable msan build on CI (actually!).

- tools/built/src/Dockerfile.msan
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/676)
> fix: Correct msan build (had typo in bazel flag).

- third_party/patches/libsodium.patch
Fixes https://app.circleci.com/pipelines/github/TokTok/c-toxcore/5592/workflows/e33eaa18-e7b7-491c-af8c-adb9dcb4a3a1/jobs/44283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/684)
> fix: Zero-init another array in libsodium.

- .gitmodules
- WORKSPACE
- third_party/curl/BUILD.bazel
- third_party/ffmpeg/BUILD.bazel
- third_party/go/BUILD.bazel
- tools/BUILD.bazel
- tools/bazelrc.boot
- tools/git-remotes
Not fully working, yet, but getting close.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/694)
> refactor: Add apigen repo; enable kotlin in WORKSPACE.

- stack.yaml
- tools/built/src/Dockerfile.haskell
Needed so docker deploys work on apigen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/696)
> chore: Add apigen to stack.yaml.

- ghc.nix
- third_party/haskell/BUILD.bazel
This contains useful extra functions for list manipulation, searches, etc. that we don't want to reimplement ourselves.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/705)
> chore: Add "extra" haskell package.

- .gitmodules
- WORKSPACE
- third_party/zig/BUILD.bazel
- third_party/zig/csource.c
- third_party/zig/csource.h
- third_party/zig/main.zig
- tools/BUILD.bazel
- tools/LICENSE.gpl3-https
- tools/built/src/home/.config/home-manager/home.nix
- tools/git-remotes
It works now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/731)
> chore: Update rules_zig and add zig-toxcore-c.

- .bazelrc
- third_party/zig/BUILD.bazel
- third_party/zig/toolchains.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/734)
> chore: Move toolchain stuff to a .bzl file.

- .bazelrc
- .github/workflows/docker.yml
We do want to build as much as we can.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/735)
> chore: Don't fail-fast in docker builds.

- ghc.nix
- third_party/haskell/BUILD.bazel
Also add a dependency for apigen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/743)
> chore: Push tokstyle changes to toktok-stack.

- tools/built/src/Dockerfile.asan
- tools/built/src/Dockerfile.msan
- tools/built/src/Dockerfile.tsan
- tools/project/build_defs.bzl
It had its own `build_tag_filters` overriding the `-no-cross` from `.bazelrc`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/744)
> fix: Fix msan build.

- tools/built/src/Dockerfile.msan
- tools/debug/symbolize
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/755)
> fix: Add `no-san` to the skipped targets in the msan build.

- .gitmodules
- stack.yaml
- tools/BUILD.bazel
- tools/built/src/Dockerfile.haskell
- tools/git-remotes
- tools/haskell/haskell_targets.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/769)
> feat: Add hs-msgpack-json to the stack.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/781)
> chore: Add warning suppression in toxins (for toxvpn).

- .bazelrc
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/783)
> docs: Add some links to other resources to readme.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/785)
> docs: Add "desktop" to the trifa material description.

- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/799)
> chore: Replace junit with kotlin-test-junit for multiplatform.

- .gitmodules
- tools/BUILD.bazel
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/800)
> feat: Add back jvm-toxcore-c to the stack.

- .bazelrc
- WORKSPACE
- tools/built/src/home/.config/home-manager/home.nix
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/801)
> chore: Add warning suppression for protobuf C++ lite runtime.

- tools/inject-repo
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/845)
> chore: Disable remote caching on cirrus for now.

- tools/project/BUILD.bazel
- tools/project/build_defs.bzl
- tools/project/common/github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/855)
> chore: Add test to ensure release drafter is set up correctly.

- tools/project/BUILD.bazel
- tools/project/build_defs.bzl
- tools/project/common/github/workflows/ci.base.yml
We do this by testing that all ci.yml files are a superset of ci.base.yml. They may have additional stuff, but they must have at least the content of that file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/858)
> feat: Add test to ensure all CI checks include the common checks.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/862)
> chore: Disable some warnings in preparation for clang upgrade.

- third_party/nixpkgs.bzl
- third_party/qt/build_defs.bzl
- tools/built/src/Dockerfile.third_party
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/863)
> chore: Upgrade to nixos 24.05.

- .bazelrc
- .gitmodules
- third_party/BUILD.ffmpeg
- tools/git-remotes
- tools/git_modules_test.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/877)
> chore: Clean up some warning flags; add wiki.

- WORKSPACE
- third_party/BUILD.bazel
- third_party/BUILD.gdk-pixbuf
- third_party/BUILD.glib
- third_party/BUILD.glib.out
- third_party/BUILD.libnotify
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/882)
> fix: Make glibconfig.h to glib so things actually compile.

- third_party/BUILD.qt
- third_party/qt/BUILD.qtbase.dev
- third_party/qt/BUILD.qtbase.out
We don't use it yet, but in case we want to reimplement libnotify in qtox, we have it available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/885)
> chore: Add QtDBus dependency.

- .bazelrc
- third_party/qt/BUILD.qtbase.dev
- third_party/qt/build_defs.bzl
- tools/built/src/Dockerfile.arm64
- tools/built/src/Dockerfile.fastbuild
- tools/built/src/Dockerfile.release
- tools/built/src/Dockerfile.windows
- tools/inject-repo
This allows us to render widgets without having a display.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/886)
> fix: Run Qt gui tests on the offscreen platform.

- third_party/BUILD.qt
- third_party/qt/BUILD.qtbase.dev
- third_party/qt/BUILD.qtsvg.dev
- third_party/qt/build_defs.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/893)
> fix: Add SVG support for Qt tests.

- .bazelrc
- WORKSPACE
- third_party/BUILD.ffmpeg
- third_party/BUILD.libcap
- third_party/BUILD.libsodium
- third_party/BUILD.libvpx
- third_party/BUILD.libzmq
- third_party/BUILD.openal
- third_party/BUILD.opus
- third_party/BUILD.sqlcipher
- third_party/BUILD.yasm
- third_party/qt/build_defs.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/894)
> chore: Start becoming compatible with bazel 7.

- .bazelrc
- tools/project/BUILD.bazel
- tools/project/build_defs.bzl
- tools/project/mkstamp.sh
- tools/project/mkstamp_c.sh
Used in qTox. Currently we hard-code a version. This will let us get it from git.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/906)
> feat: Add an `mkstamp` macro to help generate git version info.

- .bazelrc
- .bazelrc.local.example
- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/917)
> fix: Don't error on linker warnings by default.

- .bazelrc
- third_party/nixpkgs.bzl
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.third_party
- tools/built/src/setup-dev.sh
- tools/workspace/python.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/924)
> chore: add python 3.12 support

- tools/built/dev/test_dev_container.sh
- tools/built/src/Dockerfile.dev
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/925)
> fix: remove cgroup shenanigans

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- WORKSPACE
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.third_party
- tools/built/src/home/.gitconfig
- tools/built/src/setup-dev.sh
- tools/workspace/rules_nixpkgs.bzl
Disabled arm64 and windows builds because they are broken for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/927)
> chore: Upgrade to bazel 7.

- .bazelrc
- .bazelrc.local.example
- .github/workflows/ci.yml
- .github/workflows/docker.yml
- BUILD.bazel
- MODULE.bazel
- WORKSPACE
- tools/built/src/Dockerfile
- tools/built/src/Dockerfile.arm64
- tools/built/src/Dockerfile.asan
- tools/built/src/Dockerfile.debug
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.haskell
- tools/built/src/Dockerfile.msan
- tools/built/src/Dockerfile.release
- tools/built/src/Dockerfile.third_party
- tools/built/src/Dockerfile.tsan
- tools/built/src/Dockerfile.windows
- tools/built/src/home/.gitconfig
- tools/built/src/setup-dev.sh
- tools/haskell/hie-docker
- tools/workspace/rules_nixpkgs.bzl
The old way is archived and broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/928)
> chore: Add a new way of generating compile_commands.json.

- .bazelrc
- .bazelrc.local.example
- .github/workflows/ci.yml
- .github/workflows/docker.yml
- WORKSPACE
- tools/built/src/Dockerfile
- tools/built/src/Dockerfile.arm64
- tools/built/src/Dockerfile.asan
- tools/built/src/Dockerfile.debug
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.haskell
- tools/built/src/Dockerfile.msan
- tools/built/src/Dockerfile.release
- tools/built/src/Dockerfile.third_party
- tools/built/src/Dockerfile.tsan
- tools/built/src/Dockerfile.windows
- tools/built/src/home/.gitconfig
- tools/built/src/setup-dev.sh
- tools/workspace/rules_nixpkgs.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/926)
> chore: Fix arm64/windows builds.

- WORKSPACE
- third_party/BUILD.typeshed
This contains requests, which helps mypy typecheck our code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/938)
> chore: Add python/typeshed to the workspace.

- MODULE.bazel
- tools/built/src/home/.config/home-manager/home.nix
- tools/project/build_defs.bzl
- tools/project/mkstamp.sh
- tools/project/mkstamp_c.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/948)
> fix: Use a cmake-style configure for version stamp files.

- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/951)
> chore: Update Kotlin version to 2.1.0.

- third_party/.clang-format
- third_party/kimageformats.BUILD
- third_party/kimageformats/BUILD.bazel
- third_party/kimageformats/test/qimage_fuzz_test.cpp
- third_party/kimageformats/test/qimage_test.cpp
- third_party/qt/build_defs.bzl
Moving it out of qtox, because it's independent of that code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/952)
> test: Add the kimageformats fuzz test to third_party.

- .bazelrc
- WORKSPACE
- third_party/qt.BUILD
- third_party/qt/build_defs.bzl
- third_party/qt/qtremoteobjects.dev.BUILD
- third_party/qt/qtremoteobjects.out.BUILD
This allows us to do IPC/RPC in qtox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/953)
> feat: Add qtremoteobjects to the bazel build.

- .bazelrc
https://github.com/TokTok/c-toxcore/pull/2824/checks?check_run_id=35424024758
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/956)
> chore: Don't warn about stack frame size in msan (and others).

- WORKSPACE
- third_party/certifi.BUILD
- third_party/chardet.BUILD
- third_party/idna.BUILD
- third_party/requests.BUILD
- third_party/urllib3.BUILD
It's so useful and so much better than urllib.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/957)
> feat: Add python requests library to the stack.

- .bazelrc
- .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/958)
> chore: Add local bazel build (not in docker).

- WORKSPACE
- third_party/libunwind.BUILD
We may use this for stack traces in qTox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/962)
> feat: Add libunwind to the stack.

- third_party/libunwind.BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/963)
> chore: Fix local-only libunwind.

- WORKSPACE
- third_party/kimageformats/BUILD.bazel
- tools/built/src/home/.config/home-manager/home.nix
Also update some submodules and add rsync to the dev image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/992)
> chore: Upgrade kimageformats to 6.10.0.

- .gitmodules
- cspell.config.yaml
- tools/BUILD.bazel
- tools/built/src/home/.config/home-manager/home.nix
- tools/git-remotes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/995)
> feat: Add debugtox to the stack.

- compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/1003)
> fix: Add missing docker compose configs.

- stack.yaml
- tools/built/src/Dockerfile.haskell
- tools/built/src/Dockerfile.third_party
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/1005)
> chore: Update Haskell stack to the (almost) latest LTS.
