TokTok/toktok-stack

- WORKSPACE
- appveyor.yml
- third_party/BUILD.libsodium
- third_party/BUILD.libvpx
- third_party/BUILD.psocket
- third_party/BUILD.pthread
- third_party/qt/build_defs.bzl
- third_party/yasm/build_defs.bzl
- tools/bazel.rc
- tools/config/BUILD.bazel
- tools/project/build_defs.bzl
This adds some support for windows builds by adding a `@pthread` target
that either simply uses pthread installed on the system or, in the case
of windows, uses pthreads-win32.
This also adds a config option for windows and uses it for yasm (64 bit
only supported).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/38)
> Preliminary win32 support: pthreads.

- .github/settings.yml
This allows us to slightly more centrally manage repo settings. In
particular, it allows us to sync issue labels across all repos. It also
semi-supports branch protection rules, which we apply here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/64)
> Add settings.yml to manage some of the github settings.

- .cirrus.yml
- tools/BUILD.bazel
- tools/git-remotes
- tools/git_modules_test.pl
- tools/gitmodules
- tools/project/build_defs.bzl
Project lists are:
* .gitmodules
* tools/git-remotes
* tools/BUILD.bazel
Added a symlink to .gitmodules in tools/gitmodules. This is needed
because we don't have access to `//:.gitmodules`. We could easily have
access to it, but that means adding it to the toplevel BUILD.bazel, which
in turn means .gitmodules becomes part of the minimal bootstrap set we
need for building the Docker image. We'd like to avoid having to rebuild
the Docker image from scratch (6GB upload) whenever we add/remove/rename
a submodule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/71)
> Add test to make sure all project lists agree.

- third_party/curl/linux/curl_config.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/77)
> Stop using stropts.h. It disappeared in ubuntu focal.

- .bazelrc
- .bazelrc.local.example
- .travis.yml
- .ycm_extra_conf.py
- Dockerfile
- Makefile
- tools/bazelrc.boot
- tools/bazelrc.docker
- tools/kythe/builder.py
- tools/kythe/clang_tidy.py
- tools/kythe/ycm_extra_conf.py
It must be enabled in the docker image, so for simplicity, we enable it
always. To disable, you'll now need to edit tools/bazelrc.boot. It's no
longer a control in .bazerc.local.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/87)
> Enable bazel strict mode by default.

- .bazelrc
- Dockerfile
- Makefile
- tools/inject-repo
Set up the Docker image in a way such that a parameterless build works.
Local customisation in .bazelrc.local should be for things like changing
the compilation mode, adding asan, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/89)
> Allow sub-repos to bring their own .bazelrc.local.

- WORKSPACE
- third_party/BUILD.msgpack
We'll use this for toxcore packets (application layer at first, later
maybe also for lower layers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/98)
> Add msgpack-c to third_party.

- .gitignore
- third_party/BUILD.openal
This won't work on windows, but we'll fix that later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/129)
> chore: Add missing linker option to link openal to libdl.

- stack.yaml
hs-cimple now supports `static_assert`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/205)
> chore: Update submodules.

- .bazelrc
- Dockerfile
- tools/bazelrc.boot
- tools/prepare_toolchain.sh
This is now done in the bazel base image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/278)
> chore: Move Qt deps installation out of the toktok-stack image.

- .bazelrc
- .github/workflows/docker.yml
It needs the C++ runtime, which clang does not link in by default.
clang++ does, but bazel uses clang as linker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/286)
> chore: Fix asan build.

- .bazelrc
This will be used to run toxcore tests under valgrind to find
uninitialised memory errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/290)
> feat: Add valgrind config for bazel.

- .bazelrc
This speeds up rebuilds quite a bit and it seems `rules_haskell` finally
supports it (at least tested locally).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/298)
> chore(deps): Enable `--remote_download_minimal`.

- .github/workflows/docker.yml
- Makefile
- tools/built/Makefile
- tools/built/dev/Dockerfile
- tools/built/dev/init.sh
- tools/built/src/Dockerfile
- tools/built/src/Dockerfile.dev
- tools/built/src/Dockerfile.dev-hs
- tools/built/src/Dockerfile.third_party
- tools/project/haskell/cirrus.yml.in
- tools/project/update_versions.sh
* `latest-third_party` contains the rarely-changing dependencies. It can
be used as a basis for other similar third-party-only images.
* `latest` contains the latest snapshot including all (often changing)
source code of all submodules.
Also, get rid of the image versioning. Rolling release is working well for us now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/330)
> chore: Split docker build in `latest-third_party` and `latest`.

- tools/built/src/init.sh
When the user doesn't have one, builds will fail because the config
doesn't know which compiler is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/338)
> fix: Install a default .bazelrc.local on init.

- third_party/scala/BUILD.bazel
- tools/built/src/Dockerfile.haskell
Just so the haskell docker publish builds don't fail for packages that
don't have any installed tools/binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/382)
> chore: Create empty `$HOME/.local/bin` directory.

- .bazelrc
- tools/debug/BUILD.bazel
- tools/debug/flakynet.c
- tools/debug/oomer.c
- tools/debug/run_flakynet.py
- tools/debug/run_oomer
This flag currently makes 10% of `sendto` calls fail and return an error
(and set `errno` to 11). An alternative version (without `--syscalls=1`)
could simulate packet loss by dropping the packet on the floor without
telling the caller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/391)
> feat: Add `--config=flakynet` to run tests with simulated bad network.

- .github/workflows/docker.yml
docker/build-push-action action doesn't clone submodules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/407)
> fix: Use a local checkout for the buildx context in kythe build.

- third_party/BUILD.ncurses
In release mode, an assert is preprocessed out, resulting in this warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/440)
> chore: Don't warn about unused variables in ncurses.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/452)
> chore: Unset `-DNO_FRAME_POINTER` on absl compilation.

- .bazelrc
So stack traces are a bit more useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/454)
> chore: Don't strip debug info in fuzzer builds.

- .bazelrc
Also enabled `-Wframe-larger-than=20000` in bazel build. Also set the C++
standard to C++17. We're not using any of it yet, but we should be
allowed to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/468)
> chore: Set compilation mode to debug in sanitizers.

- .bazelrc
- WORKSPACE
- third_party/BUILD.bazel
- third_party/BUILD.tox_extension_messages
- third_party/BUILD.toxext
We're not importing this stuff into toktok-stack proper, but qtox
depends on it, so we'll treat it as third party dependency and don't
need to apply the same quality standards we apply to proper TokTok
projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toktok-stack/476)
> chore: Add toxext stuff to third_party.

- WORKSPACE
- third_party/rust/BUILD.bazel
- third_party/rust/main.rs
We don't use it, and it consumes a lot of disk space.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/640)
> chore: Remove rust support in toktok-stack.

- tools/built/src/Dockerfile.dev
- tools/built/src/init.sh
The latter because it helps vim YCM find gtest headers. It shouldn't be necessary, but I haven't figured out the real fix yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/642)
> chore: Update ci-tools and tokstyle; add cppcheck and libgtest-dev.

- .bazelrc
`action_env` also works for `bazel run`.
Taken from
https://github.com/robinlinden/hastur/blob/275bc883dc5f55ef3b01f313886c25830a10335e/.bazelrc#L53-L97
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/646)
> feat: Add more strict asan options; use `action_env` instead of `test_env`

- tools/built/src/Dockerfile.third_party
They silently stopped creating their working directory, so now we need to create it in the image. Very annoying, because now Cirrus no longer supports arbitrary images, because they need to have that tmp directory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/651)
> fix: Make Cirrus CI work again.

- tools/built/src/Dockerfile
- tools/built/src/Dockerfile.third_party
- tools/workspace/cleanup
There's about 661MiB of docs in the haskell distribution, which is copied over twice, so it's 1322MiB of docs (out of currently 7.5GiB of bazel cache after the initial aquery).
GitHub Actions runs out of disk space when producing the layers for upload. Afterwards, during CI runs, it's fine, but while uploading/compressing layers, it needs to replicate all the files in the layer, so it takes up a lot of additional disk space all at once.
Another future thing we can do is split the layer, e.g. by doing `query` and then `aquery` to first download some things and then extract them and download more.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/661)
> perf: Attempt to reduce disk usage for building docker images.

- .bazelrc
- third_party/go/BUILD.bazel
- tools/built/src/Dockerfile.msan
It moderately works. It works well for pure C code, but not for C++ (definitely not Qt) and not for the fuzzers because of a dependency on msan_interface.h, which is not available in the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/674)
> cleanup: Re-enable msan build.

- .bazelrc
- .github/workflows/ci.yml
- WORKSPACE
- third_party/patches/libsodium.patch
- tools/built/src/setup-dev.sh
libsodium still breaks msan without this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/682)
> fix: Add back the libsodium msan patch.

- WORKSPACE
- third_party/BUILD.libllvm
So it's available in msan errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/683)
> chore: Add llvm-symbolizer to third party.

- .bazelrc
- .ycm_extra_conf.py
- WORKSPACE
- third_party/kotlin/BUILD.bazel
- third_party/kotlin/Main.kt
- tools/bazelrc.boot
It's quite broken right now. To build `//third_party/kotlin:mytest`, do:
```sh
nix-shell -p jdk11.home --run "bazel run //third_party/kotlin:mytest"
chmod 755 \
external/remote_java_tools_linux/java_tools/src/tools/singlejar/singlejar_local \
external/remote_java_tools_linux/java_tools/ijar/ijar
nix-shell -p patchelf --run "patchelf \
--set-interpreter /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 \
--add-rpath /nix/store/yazs3bdl481s2kyffgsa825ihy1adn8f-gcc-12.2.0-lib/lib \
external/remote_java_tools_linux/java_tools/src/tools/singlejar/singlejar_local"
nix-shell -p patchelf --run "patchelf \
--set-interpreter /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 \
--add-rpath …
```
> feat: Add Kotlin support (disabled because it's broken).

- WORKSPACE
Fixes libsodium hash mistmatch and xz failing to download.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/835)
> chore: Fix dependency errors

- WORKSPACE
- tools/built/dev/setup-local.sh
This one renames `zig_package` to `zig_module` while keeping the former for compat. This allows us to upgrade zig-toxcore-c without knife-cut.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/850)
> chore: Update to zig rules 0.4.0.

- ghc.nix
- third_party/haskell/BUILD.bazel
We need to migrate to this as ansi-wl-pprint is deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/853)
> chore: Add prettyprinter haskell deps.

- WORKSPACE
- third_party/BUILD.glib
- third_party/BUILD.libnotify
Needed for qtox desktop notifications on linux.
Ideally we'd build this in the bazel build, but nixpkgs is second best.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/881)
> chore: Add libnotify to bazel build.

- third_party/qt/build_defs.bzl
We need this for reproducible builds and better caching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/892)
> fix: Use Qt RCC format version 1 to avoid storing mtime.

- tools/built/src/Dockerfile.third_party
We need it for bazel 7. For bazel 6, it's also good practice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/907)
> chore: Add MODULE.bazel to the docker image early on.

- .bazelrc
Apparently `snprintf` is marked unused, but lots of things use it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/931)
> chore: Add warning suppression for release builds.

- .bazelrc
- .clang-format
- .github/workflows/ci.yml
- WORKSPACE
- third_party/libsodium/BUILD.bazel
- third_party/libsodium/libsodium_test.c
- third_party/simdjson.BUILD
This one is quite fast. If we ever need to do fast json parsing, this is the one for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/982)
> feat: Add simdjson to the stack.

- .gitmodules
- cspell.config.yaml
- tools/BUILD.bazel
- tools/built/src/home/.config/home-manager/home.nix
- tools/git-remotes
- tools/project/build_defs.bzl
- tools/project/common/github/workflows/draft.base.yml
So that it can have Python modules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/997)
> chore: Rename ci-tools to ci_tools.

- compose.yml
It fails at linking toxcore into hs-toxcore-c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toktok-stack/1004)
> fix: Debug build can't use haskell code for now.
